version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/Oslo
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">= 13.a, < 14"
  - dependency-name: "@types/node"
    versions:
    - ">= 14.a, < 15"
  - dependency-name: typedoc
    versions:
    - 0.20.20
    - 0.20.22
    - 0.20.24
    - 0.20.25
    - 0.20.26
    - 0.20.27
    - 0.20.28
    - 0.20.29
    - 0.20.30
    - 0.20.31
    - 0.20.32
    - 0.20.33
    - 0.20.34
    - 0.20.35
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.2
  - dependency-name: "@types/node"
  - dependency-name: "typescript"
